siteName: Mind the mind now!
productionUrl: https://www.mindthemind-now.org/
logo: ''
htmlHead: |-
  <link rel="icon" href="/assets/files/icons/favicon-adapt.svg" type="image/svg+xml">
  <script defer src="https://cloud.umami.is/script.js" data-website-id="141baef0-51f1-4308-b711-16bc55c657c6"></script>
cssHead: ''
languages:
  - code: fr
    status: published
    name: Français
    customUrlPrefix:
      prefix: ''
    isCmsDefault: false
    isWebsiteDefault: false
  - code: en
    status: draft
    keepUrlPrefix: false
collections:
  - people
  - articles
