siteName: Mind the mind now!
productionUrl: https://www.mindthemind-now.org/
logo: /_images/humanmindrightsnow-sansfondnettoye.webp
htmlHead: <link rel="icon" href="/assets/files/icons/favicon-adapt.svg" type="image/svg+xml">
cssHead: ''
languages:
  - code: fr
    status: published
    name: Français
    customUrlPrefix:
      prefix: ''
    isCmsDefault: false
    isWebsiteDefault: false
  - code: en
    status: draft
    keepUrlPrefix: false
collections:
  - people
  - articles
