siteName: Mind the mind now!
productionUrl: https://www.mindthemind-now.org/
htmlHead: <link rel="icon" href="/assets/files/icons/favicon-adapt.svg" type="image/svg+xml">
languages:
  - code: fr
    name: Français
    customUrlPrefix:
      prefix: ''
    status: published
    isCmsDefault: false
    isWebsiteDefault: false
collections:
  - people
